services:
  xlsft_ru:
    environment:
      MODE: production
      DB_PASSWORD: ${DB_PASSWORD}
      TG_USER: ${TG_USER}
      TG_TOKEN: ${TG_TOKEN}
    restart: always
    build:
      context: .
      dockerfile_inline: |
        FROM node:20-slim AS base
        ENV PNPM_HOME="/pnpm"
        ENV PATH="$PNPM_HOME:$PATH"
        RUN corepack enable
        FROM base AS prod
        WORKDIR /app
        COPY .npmrc ./
        COPY package*.json ./
        COPY pnpm-lock.yaml ./
        RUN pnpm fetch --prod
        COPY . .
        RUN pnpm run build
        FROM base
        COPY --from=prod /app/node_modules /app/node_modules
        COPY --from=prod /app/dist /app/dist
        CMD ["node", ".output/server/index.mjs"]
    ports:
      - "4001:3000"
