FROM node:alpine AS builder

WORKDIR /app/bot
RUN npm install -g pnpm

COPY bot/package.json ./
RUN pnpm install --ignore-scripts

COPY bot ./
COPY global.config.ts ../global.config.ts
COPY schema ../schema
COPY i18n ../i18n
RUN pnpm run build

FROM node:alpine AS runtime

WORKDIR /app/bot
COPY --from=builder /app/bot/dist ./dist
COPY --from=builder /app/bot/node_modules ./node_modules
COPY --from=builder /app/bot/package.json ./

ENTRYPOINT ["node", "dist/server.js"]